apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: gateway-runtime-rebff
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: gateway-runtime-rebff
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 8080
  egress:
    - {}
