apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-runtime-rebff
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway-runtime-rebff
  endpoints:
    - port: http
      path: /portal/metrics
      interval: 30s
      scrapeTimeout: 5s
